apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-storage
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true

parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-01ce24f282db7fcdd
    