apiVersion: v1
kind: Pod
metadata:
  name: "my-app"
  namespace: jjtech-project
  labels:
    app: "my-app"
spec:
  containers:
  - name: tower-container
    image: "nginx"
    resources:
      limits:
          cpu: 200m
          memory: 500Mi
          requests: cd
      cpu: 100m
      memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
    